### ISSUE TITLE
git identifies this project as dftbplus-18.1 when the project name is mpifx

### ISSUE THREAD

**Issue by yurivict** [dftbplus/mpifx#8]
Could you please adjust it?

Thanks!

**Comment by aradi** [comment]
Not sure, what you mean. We use tags in the mpifx project, which marks the revisions needed for a given official dftbplus release. (Although, I just realized, that I've forgotten to add tag `dftbplus-18.2`) to it. We did not have a proper release for mpifx itself, so the `dftbplus-*` tags are the only ones in the repository so far. Does this cause any confusion for your building / packaging efforts?

**Comment by yurivict** [comment]
This is ok, don't worry about this!
